# Generated by Django 3.0.8 on 2020-07-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaapp', '0002_auto_20200725_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
